#write a Program to achieve the (a^m)^n
print("*"*40)
print('\t Calculate the (a^m)^n - Way1:')
print("*"*40)
a = float(input('Enter \'a\' value(numeric only):'))
m = float(input('Enter \'m\' value(numeric only):'))
n = float(input('Enter \'n\' value(numeric only):'))
r1 = (a**m)**n
print("-"*40)
print('\t Calculate value of (a+b)^2 is : {}'.format(r1))
print("-"*40)
print('\t Calculate the (a+b)^2 - Way2:')
r2 = a**(m*n)
print("-"*40)
print('\t Calculate value of (a+b)^2 is : {}'.format(r2))
print("-"*40)